/*
 * ultrasonic.h
 *
 *  Created on: Oct 24, 2021
 *      Author: Aly Maher
 */

#ifndef ULTRASONIC_H_
#define ULTRASONIC_H_

#include "../MCAL/icu.h"
#include "../MCAL/gpio.h"
#include <util/delay.h>
#include "../LIBS/std_types.h"
#include "../LIBS/Utils.h" /* To use the macros like SET_BIT */

#include <avr/io.h>


void Ultrasonic_init(void);
/*
 * Description :
 * 1-Initialize the ICU driver as required.
 * 2-Setup the ICU call back function.
 * 3-Setup the direction for the trigger pin as output pin through the GPIO driver.
 * 		Inputs: None
 * 		Return: None
*/
void Ultrasonic_Trigger(void);
/*
 * Description :
 * 	1-Send the Trigger pulse to the ultrasonic.
 * 		Inputs: None
 * 		Return: None
*/
uint16 Ultrasonic_readDistance(void);
/*
 * Description:
 * Send the trigger pulse by using Ultrasonic_Trigger function.
 * Start the measurements by the ICU from this moment.
 * Inputs: None
 * Return: The measured distance in Centimeter.
*/
void Ultrasonic_edgeProcessing(void);
/*
 * Description :
 * This is the call back function called by the ICU driver.
 * This is used to calculate the high time (pulse time) generated by the ultrasonic sensor.
 * Inputs: None
 * Return: None
*/
#endif /* ULTRASONIC_H_ */
